version: 0.0
os: linux
files:
  - source: .
    destination: /usr/share/nginx/html/
hooks:
   BeforeInstall:
    - location: scripts/install_dependences.sh
      timeout: 300
      runas: root
      
  AfterInstall:
    - location: scripts/set_permissions.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: root
